apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-from-scratch
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: application-from-helm
      ## use valueFiles instead
      # parameters:
      #   - name: "replicaCount"
      #     value: "2"
      valueFiles:
        - custom-values.yaml # custom values file to override default values.yaml in the helm chart
    repoURL: https://github.com/gr8coder8/learning-argocd.git
    targetRevision: master
    path: v03-argocd-applications/helm/nginx # helm manifests location. See application-2.yaml for directly referencing helm chart