apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-from-scratch
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/gr8coder8/learning-argocd.git
    targetRevision: master
    path: v03-argocd-applications/helm/nginx