apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-directory
  namespace: argocd
spec:
  destination:
    namespace: directory
    server: https://kubernetes.default.svc
  project: default
  source:
    directory: # like helm, here it is directory
      # recurse: true
      # exclude: 'serviceaccount.yaml' # exclude only this file
      # include: '{serviceaccount.yaml,service.yaml}' # include only these files but exclude all others
    path: v03-argocd-applications/directoryOfmanifests/ # directory
    repoURL: https://github.com/gr8coder8/learning-argocd.git
    targetRevision: master